### ISSUE TITLE
Glossary #1 - Intercept? 

### ISSUE THREAD

**Issue by giangnguyen2412** [giangnguyen2412/InterpretableMLBook-Vietnamese#2]
Trong quá trình dịch, mình gặp thuật ngữ này. Ngữ cảnh đây:

> 
![image](https://user-images.githubusercontent.com/30857111/85397852-43c29d80-b58f-11ea-9a5f-6d19db0a861d.png)

Mình định dịch là giá trị chặn, mọi người có ý kiến gì không?

**Comment by ledinhtri97** [comment]
Em có ý kiến là các trọng số học **β** là các hệ số trong hàm tuyến tính nên có thể ta gọi **β_0** là hệ số chặn.

**Comment by giangnguyen2412** [comment]
> Em có ý kiến là các trọng số học **β** là các hệ số trong hàm tuyến tính nên có thể ta gọi **β_0** là hệ số chặn.

Đồng ý, vậy sẽ dịch là hệ số chặn nhé.
