### ISSUE TITLE
Glossary #2 - least squares error 

### ISSUE THREAD

**Issue by giangnguyen2412** [giangnguyen2412/InterpretableMLBook-Vietnamese#3]
Trong bảng thuật ngữ của cuốn Đắm mình vào học sâu, thuật ngữ này được dịch là Tối thiểu bình phương sai số. Tuy nhiên theo mình thấy nên dịch là Sai số bình phương tối thiểu sẽ thuận hơn. Tương tự với MSE, RMSE v.v..

**Comment by ledinhtri97** [comment]
Em đồng ý, vì theo ý kiên riêng em cũng thấy cụm ```Tối thiểu bình phương sai số``` tạo cảm giác như động từ. Trong khi đó ```Sai số bình phương tối thiểu``` đúng danh từ, thấy tự nhiên hơn
