### ISSUE TITLE
Discussion #1 - Giá trị bình phương R

### ISSUE THREAD

**Issue by giangnguyen2412** [giangnguyen2412/InterpretableMLBook-Vietnamese#4]
Mình đang đọc đoạn này, tuy nhiên không đồng ý với tác giả:
![image](https://user-images.githubusercontent.com/30857111/85752227-31d72b00-b746-11ea-98bf-f6f8904e3ad5.png)

Đoạn này nằm ở chương 4.1.1. Tác giả có nói:

> There is a catch, because R-squared increases with the number of features in the model, even if they do not contain any information about the target value at all.

Tuy nhiên dựa vào công thức tính R ở trên theo SSE và SST, ta không thể đưa ra quyết định như tác giả.
Bởi vì, nếu p tăng (p là số lượng đặc trưng), vì mô hình là tuyến tính, $y^i$ cũng sẽ tăng, trong khi ground truth không đổi,  nên SSE sẽ tăng, trong khi SST undetermined.

**Comment by ledinhtri97** [comment]
Em thì vẫn đồng ý với tác giả. Ý kiến em như thế này anh @luulinh90s tham khảo thử : 

Vì trước hết xét khả năng của R^2 là nó đánh giá mô hình hồi quy tuyến tính đặc tả cho dữ diệu như thế nào. R^2 càng cao thì mô hình biểu diễn dữ liệu càng tốt. 

Khi đó theo cách tính R^2 truyền thống thì khi ta tăng số lượng đặc trưng (p). Mô hình (y) càng khớp với dữ liệu hơn thì SSE sẽ giảm (vì đây là độ đo giữa dự đoán với nhãn) và SST thì không đổi. Do đó R^2 tăng theo. 

Nhưng điều này không đảm bảo sự chính sác, vì có thể tăng số lượng (p) nhưng chưa chắc khả năng đặc tả của mô hình tốt cho dữ liệu vì có thể những đặc trưng đó không có giá trị học. Ngoài ra thì mô hình sẽ phức tạp hơn nếu có quá nhiều đặc trưng được thêm vào.

Do đó công thức điểu chỉnh mới của R^2, khi thêm (n-1)/(n-1-p) và số lượng đặc trưng tăng giá trị này sẽ giảm, làm cân bằng với SSE/SST tăng. Thì R^2 sẽ không bị ảnh hưởng tăng theo số lượng p không mong muốn. Vẫn đánh giá tốt hơn mô hình.

Có một bài post tham khảo thêm về công thức R^2 điều chỉnh này: [link](https://blog.minitab.com/blog/adventures-in-statistics-2/multiple-regession-analysis-use-adjusted-r-squared-and-predicted-r-squared-to-include-the-correct-number-of-variables#:~:text=The%20adjusted%20R%2Dsquared%20is,less%20than%20expected%20by%20chance.)

**Comment by giangnguyen2412** [comment]
hi Trí, theo anh hiểu và trong bài e gửi, thì adjusted R-squared chỉ phụ thuộc vào meaningful features đúng ko? Tuy nhiên trong công thức anh không thấy điều đó, mà adjusted R-squared vẫn phụ thuộc vào số lượng p đơn thuần. Không biết anh hiểu vậy đúng ko?

**Comment by ledinhtri97** [comment]
Hi anh @luulinh90s 

```adjusted R-squared chỉ phụ thuộc vào meaningful features đúng ko?```: Đúng rồi anh, vì chỉ meaningful features mới làm mô hình đặc tả dữ liệu tốt hơn.

```Tuy nhiên trong công thức anh không thấy điều đó```: Công thức điều chỉnh chỉ có thể ngăn cho việc đánh giá mô hình qua số lượng q tăng làm R^2 tăng thôi làm đánh giá công bằng hơn công thức R^2 truyền thống, vì hiện tại ta không có cách nào xác định feature nào là tốt ngoài bằng cách thử nghiệm thực tế rồi đánh giá mô hình.

**Comment by ledinhtri97** [comment]
![bestsubsetsex](https://user-images.githubusercontent.com/16860306/85814357-f19c9a80-b78f-11ea-9d40-12ede425d865.gif)

Cũng trong bài đăng em gửi link thì có thí nghiệm với 4, 5 features thì R^2(adj) thấp hơn 1,2,3 features, và theo đánh giá thì với 3 features là tốt nhất trong 5 thí nghiệm. Trong khi R^2 tăng dần với số features không thể hiện đúng mô hình tương ứng.

**Comment by giangnguyen2412** [comment]
Nice! Cám ơn em.
