### ISSUE TITLE
Features translation - Chapter 3 - 3.1 

### ISSUE THREAD

**Issue by tungnguyen1234** [giangnguyen2412/InterpretableMLBook-Vietnamese#5]
Chào mọi người, hiện tại có một số từ em dịch như sau. Mong mọi người cho ý kiến ạ, vì có một số từ em thấy hơi khó dịch sát nghĩa.

- Casual users: người dùng thông thường

- Về thời tiết:
+ Trời quang (clear), ít mây (few clouds), hơi mây (partly cloudy), hoặc nhiều mây (cloudy).
+ Sương (mist), sương + mây vụn (broken clouds).
+ mưa nhẹ + dông (thunderstorm) + mây rải rác (scattered clouds)
+ Mưa nặng (heavy rain) + mưa tuyết nhẹ (ice pellets)

- Xử lý tương đối (slightly processing)
- Trang chứa GitHub (Github repository)

Em cảm ơn.

**Comment by giangnguyen2412** [comment]
`slightly processing` : xử lý thô thì chuẩn hơn nhỉ. 
những từ còn lại a ko có ý kiến gì.

**Comment by hoangnhxda** [comment]
Anh thấy xử lý tương đối thì chuẩn hơn, còn xử lý thô nó là 1 nghĩa khác rồi

**Comment by giangnguyen2412** [comment]
2 cái này khác nhau như thế nào trong ML, anh @hoangnhxda có thể giải thích giúp em được ko ạ?

**Comment by hoangnhxda** [comment]
Xử lý thô là 1 tập dữ liệu em lấy trực tiếp từ terminal device rồi xử lý để thành dữ liệu chuẩn đầu vào của neural network, còn slightly processing là em có thể chỉ xử lý qua, điền 1 vài ô dữ liệu còn thiếu, hoặc bị Null

**Comment by tungnguyen1234** [comment]
Em thấy xử lý tương đối ổn ạ.
