### ISSUE TITLE
Chapter 5 - 5.1: Partial Dependence Plot

### ISSUE THREAD

**Issue by tungnguyen1234** [giangnguyen2412/InterpretableMLBook-Vietnamese#6]
Chào các anh chị, hiện tại em có những từ dịch như sau:

- Partial Dependence Plot: Đồ thị đặc trưng riêng. 

- Instances: các hàng dữ liệu được chọn. Từ này ở trong câu: "In this formula ... and n is the number of instances in the dataset." Từ này nếu có được cách dịch ngắn hơn thì ổn hơn ạ.

- marginal effect: ảnh hưởng biên.

- categorical feature: đặc trưng phân loại.

Theo mọi người có góp ý ra sao về cách dịch trên? Em cảm ơn.

**Comment by giangnguyen2412** [comment]
`Plot` a đang dịch là phác họa chứ k dịch là đồ thị, nên `Partial Dependence Plot` a sẽ dịch là `Phác họa bán phụ thuộc`.
`Instances`: A nghĩ có thể dịch là thể hiện, nhưng nó là một mẫu dữ liệu đầu vào cho việc huấn luyện, nên mình có thể dịch là  `mẫu dữ liệu`.
`categorical feature`: a đang dịch là đặc trưng kiểu hạng mục, tham khảo cuốn Dive2DL cũng thấy dịch vậy.

**Comment by tungnguyen1234** [comment]
Mấy từ khác em thấy OK. Còn từ partial nếu dịch là "bán" thì sẽ khó phân biệt với từ semi, như trong cuốn ML cơ bản thì dịch semi-supervised learning là "học bán giám sát."  
 
Với lý do em dùng từ "riêng" cho partial là VN mình dịch PDE là phương trình đạo hàm riêng, thì chữ riêng sẽ có cơ sở hơn.

**Comment by giangnguyen2412** [comment]
Đồng ý với @tungnguyen1234
