### ISSUE TITLE
Chapter 5 - 5.1 - The remaining

### ISSUE THREAD

**Issue by tungnguyen1234** [giangnguyen2412/InterpretableMLBook-Vietnamese#9]
Chào mọi người, hiện tại phần cuối của 5.1 em có những từ thắc mắc như sau:

- _Rug_ trong câu "This problem is easily solved by showing a _rug_ (indicators for data points on the x-axis) or a histogram." Em tìm trong link, "https://www.mathworks.com/matlabcentral/fileexchange/27582-rug-plots," họ giải thích rug plot là biểu đồ thể hiện marginal distribution của hai trục xy." Thì em định có thể giữ nguyên từ rồi thêm link để người đọc hiểu chứ cũng thấy hơi khó dịch từ này.

- Accumulated Local Effect plot thì em phân vân giữa "phác họa _tích tụ/tích lũy_ ảnh hưởng cục bộ." 

- Heterogeneous effect thì em băn khoăn giữa "ảnh hưởng _không đồng nhất/dị tính_." 

- Individual conditional expectation curve thì em dịch là "đồ thị điều kiện kỳ vọng riêng biệt."

Mọi người có đề xuất ra sao về những cách dịch trên?

**Comment by giangnguyen2412** [comment]
1. A thấy làm thế là hợp lý, có thể dùng \href{https://www.mathworks.com/matlabcentral/fileexchange/27582-rug-plots}{rug} để giúp ng đọc link trực tiếp tới link này.
2. Tích lũy a thấy chuẩn hơn vì tích tụ có thể bị hiểu chệch sang cùng nghĩa với congregate
3. Ảnh hưởng không đồng nhất IMO vì sử dụng Hán-Việt đôi khi gây khó hiểu
4. conditional expectation nghĩa là kì vọng có điều kiện, do đó a đề xuất là: đồ thị kỳ vọng có điều kiện riêng biệt

**Comment by tungnguyen1234** [comment]
Em thấy OK rồi ạ.
